import './Alta/Alta_regular.otf'
import './Alta/Alta_caption.otf'
import './Alta/Alta_light.otf'

import './Lexend_Mega/static/LexendMega-Black.ttf'
import './Lexend_Mega/static/LexendMega-Bold.ttf'
import './Lexend_Mega/static/LexendMega-ExtraBold.ttf'
import './Lexend_Mega/static/LexendMega-ExtraLight.ttf'
import './Lexend_Mega/static/LexendMega-Light.ttf'
import './Lexend_Mega/static/LexendMega-Medium.ttf'
import './Lexend_Mega/static/LexendMega-Regular.ttf'
import './Lexend_Mega/static/LexendMega-SemiBold.ttf'
import './Lexend_Mega/static/LexendMega-Thin.ttf'

import './League_Gothic/static/LeagueGothic/LeagueGothic-Regular.ttf'
import './League_Gothic/static/LeagueGothic_Condensed/LeagueGothic_Condensed-Regular.ttf'
import './League_Gothic/static/LeagueGothic_SemiCondensed/LeagueGothic_SemiCondensed-Regular.ttf'

import './Amalfi Coast.ttf'

import './Josefin_Sans/static/JosefinSans-Bold.ttf'
import './Josefin_Sans/static/JosefinSans-BoldItalic.ttf'
import './Josefin_Sans/static/JosefinSans-ExtraLight.ttf'
import './Josefin_Sans/static/JosefinSans-ExtraLightItalic.ttf'
import './Josefin_Sans/static/JosefinSans-Italic.ttf'
import './Josefin_Sans/static/JosefinSans-Light.ttf'
import './Josefin_Sans/static/JosefinSans-LightItalic.ttf'
import './Josefin_Sans/static/JosefinSans-Medium.ttf'
import './Josefin_Sans/static/JosefinSans-MediumItalic.ttf'
import './Josefin_Sans/static/JosefinSans-Regular.ttf'
import './Josefin_Sans/static/JosefinSans-SemiBold.ttf'
import './Josefin_Sans/static/JosefinSans-SemiBoldItalic.ttf'
import './Josefin_Sans/static/JosefinSans-Thin.ttf'
import './Josefin_Sans/static/JosefinSans-ThinItalic.ttf'
