name: 'Deploy to Production'

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 'Run Build and Deploy'
    uses: ./.github/workflows/run-terraform-build-and-deploy.yml
    with:
      DEPLOY_ENV: 'prod'
    secrets:
      AWS_ACCESS_KEY_ID: secret.AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: secret.AWS_SECRET_ACCESS_KEY
      AWS_REGION: secret.AWS_REGION
