name: 'Deploy to QA'

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 'Run Build and Deploy'
    uses: ./.github/workflows/run-terraform-build-and-deploy.yml
    with:
      DEPLOY_ENV: 'qa'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
